Function.prototype.inheritsFrom=function(a){a.constructor==Function?(this.prototype=new a,this.prototype.constructor=this,this.prototype.parent=a.prototype):(this.prototype=a,this.prototype.constructor=this,this.prototype.parent=a);return this};function mergeObjects(a,b){var c={},d;for(d in a)c[d]=a[d];for(d in b)c[d]=b[d];return c}function mergeWithDefault(a,b){var c=defaultIfUndefined(a,b);return c=mergeObjects(b,a)}function defaultIfUndefined(a,b){return typeof a=="undefined"?b:a}
function Doodle(a){this.context=a;this.children=[]}Doodle.prototype.draw=function(){for(var a=0;a<this.children.length;a++)this.context.save(),this.children[a].draw(this.context),this.context.restore()};function Drawable(a){a=mergeWithDefault(a,{left:0,top:0,visible:!0,theta:0});this.left=a.left;this.top=a.top;this.visible=a.visible;this.theta=a.theta}Drawable.prototype.draw=function(){console.log("ERROR: Calling unimplemented draw method on drawable object.")};
function Primitive(a){a=mergeWithDefault(a,{lineWidth:1,color:"black"});Drawable.call(this,a);this.lineWidth=a.lineWidth;this.color=a.color}Primitive.inheritsFrom(Drawable);function Text(a){a=mergeWithDefault(a,{content:"",fill:"black",font:"12pt Helvetica",height:12});Drawable.call(this,a);this.content=a.content;this.fill=a.fill;this.font=a.font;this.height=a.height}Text.inheritsFrom(Drawable);
Text.prototype.draw=function(a){a.fillStyle=this.fill;a.font=this.font;a.fillText(this.content,this.left,this.height)};function DoodleImage(a){a=mergeWithDefault(a,{width:-1,height:-1,src:""});Drawable.call(this,a);this.width=a.width;this.height=a.height;this.src=a.src}DoodleImage.inheritsFrom(Drawable);DoodleImage.prototype.draw=function(a){var b=new Image,c=this.left,d=this.top,e=this.width,f=this.height;b.onload=function(){a.drawImage(b,c,d,e,f)};b.src=this.src};
function Line(a){a=mergeWithDefault(a,{startX:0,startY:0,endX:0,endY:0});Primitive.call(this,a);this.startX=a.startX;this.startY=a.startY;this.endX=a.endX;this.endY=a.endY}Line.inheritsFrom(Primitive);Line.prototype.draw=function(a){a.beginPath();if(typeof this.lineWidth!="undefined")a.lineWidth=this.lineWidth;if(typeof this.color!="undefined")a.strokeStyle=this.color;a.moveTo(this.startX,this.startY);a.lineTo(this.endX,this.endY);a.closePath();a.stroke()};
function Path(a){a=mergeWithDefault(a,{type:"straight",points:[]});Primitive.call(this,a);this.type=a.type;this.points=a.points}Path.inheritsFrom(Primitive);
Path.prototype.draw=function(a){a.beginPath();a.moveTo(this.points[0].x,this.points[0].y);if(typeof this.lineWidth!="undefined")a.lineWidth=this.lineWidth;if(typeof this.color!="undefined")a.strokeStyle=this.color;switch(this.type){case "straight":for(var b=1;b<this.points.length;b++){var c=this.points[b];a.lineTo(c.x,c.y)}break;case "quadratic":for(b=1;b<this.points.length;b++)c=this.points[b],a.quadraticCurveTo(c.cp1x,c.cp1y,c.x,c.y);break;case "bezier":for(b=1;b<this.points.length;b++)c=this.points[b],
a.bezierCurveTo(c.cp1x,c.cp1y,c.cp2x,c.cp2y,c.x,c.y)}a.stroke()};function Arc(a){a=mergeWithDefault(a,{centerX:0,centerY:0,radius:0,startingTheta:0,endingTheta:0,counterclockwise:!1});Primitive.call(this,a);this.centerX=a.centerX;this.centerY=a.centerY;this.radius=a.radius;this.startingTheta=a.startingTheta;this.endingTheta=a.endingTheta;this.counterclockwise=a.counterclockwise}Arc.inheritsFrom(Primitive);
Arc.prototype.draw=function(a){a.beginPath();if(typeof this.lineWidth!="undefined")a.lineWidth=this.lineWidth;if(typeof this.color!="undefined")a.strokeStyle=this.color;a.arc(this.centerX,this.centerY,this.radius,this.startingTheta,this.endingTheta,this.counterclockwise);a.stroke()};function Container(a){a=mergeWithDefault(a,{width:100,height:100,fill:!1,borderColor:"black",borderWidth:0});Drawable.call(this,a);this.children=[]}Container.inheritsFrom(Drawable);Container.prototype.draw=function(){};
function PolygonContainer(a){a=mergeWithDefault(a,{radius:100,sides:3,centerX:100,centerY:100,polygonTheta:0});Container.call(this,a)}PolygonContainer.inheritsFrom(Container);
window.onload=function(){var a=document.getElementById("myCanvas").getContext("2d"),b=new Doodle(a);a.save();a=new Path({color:"black",lineWidth:10,type:"straight",points:[{x:0,y:0},{x:660,y:0},{x:660,y:480},{x:0,y:480},{x:0,y:0}]});b.children.push(a);var a=new Path({color:"black",lineWidth:10,type:"quadratic",points:[{x:140,y:100},{cp1x:15,cp1y:130,x:90,y:180},{cp1x:215,cp1y:230,x:65,y:260}]}),c=new Path({color:"red",lineWidth:8,type:"quadratic",points:[{x:140,y:100},{cp1x:15,cp1y:130,x:90,y:180},
{cp1x:215,cp1y:230,x:65,y:260}]});b.children.push(a);b.children.push(c);a=new Path({color:"black",lineWidth:10,type:"straight",points:[{x:290,y:100},{x:210,y:140},{x:290,y:220},{x:210,y:270}]});c=new Path({color:"red",lineWidth:8,type:"straight",points:[{x:290,y:100},{x:210,y:140},{x:290,y:220},{x:210,y:270}]});b.children.push(a);b.children.push(c);a=new Path({color:"black",lineWidth:10,type:"bezier",points:[{x:340,y:105},{cp1x:340,cp1y:310,cp2x:460,cp2y:310,x:460,y:110}]});c=new Path({color:"red",
lineWidth:8,type:"bezier",points:[{x:340,y:105},{cp1x:340,cp1y:310,cp2x:460,cp2y:310,x:460,y:110}]});b.children.push(a);b.children.push(c);var a=new Line({startX:510,startY:115,endX:590,endY:115,lineWidth:10,color:"black"}),c=new Line({startX:510,startY:275,endX:590,endY:275,lineWidth:10,color:"black"}),d=new Line({startX:550,startY:115,endX:550,endY:275,lineWidth:10,color:"black"}),e=new Line({startX:510,startY:115,endX:590,endY:115,lineWidth:8,color:"red"}),f=new Line({startX:510,startY:275,endX:590,
endY:275,lineWidth:8,color:"red"}),g=new Line({startX:550,startY:115,endX:550,endY:275,lineWidth:8,color:"red"});b.children.push(a);b.children.push(c);b.children.push(d);b.children.push(e);b.children.push(f);b.children.push(g);a=new Arc({color:"black",lineWidth:6,centerX:180,centerY:360,radius:49,startingTheta:Math.PI*0.25,endingTheta:Math.PI*1.75,counterclockwise:!1});c=new Line({color:"black",lineWidth:4,startX:180,startY:360,endX:216.5,endY:396.5});d=new Line({color:"black",lineWidth:4,startX:180,
startY:360,endX:216.5,endY:323.5});b.children.push(a);b.children.push(c);b.children.push(d);for(c=0;c<15;c++)a=new Arc({color:"yellow",lineWidth:6,centerX:180,centerY:360,radius:50*(c/15),startingTheta:Math.PI*0.25,endingTheta:Math.PI*1.75,counterclockwise:!1}),b.children.push(a);a=250;for(c=0;c<3;c++)d=new DoodleImage({src:"cherry.jpg",left:a,top:310,width:100,height:100}),b.children.push(d),a+=110;a=new Text({left:360,height:440,content:"Om nom nom"});b.children.push(a);b.draw()};