Function.prototype.inheritsFrom=function(a){a.constructor==Function?(this.prototype=new a,this.prototype.constructor=this,this.prototype.parent=a.prototype):(this.prototype=a,this.prototype.constructor=this,this.prototype.parent=a);return this};function mergeObjects(a,b){var c={},d;for(d in a)c[d]=a[d];for(d in b)c[d]=b[d];return c}function mergeWithDefault(a,b){var c=defaultIfUndefined(a,b);return c=mergeObjects(b,a)}function defaultIfUndefined(a,b){return typeof a=="undefined"?b:a}
function Doodle(a){this.context=a;this.children=[]}Doodle.prototype.draw=function(){for(var a=0;a<this.children.length;a++)this.context.save(),this.children[a].draw(this.context),this.context.restore()};function Drawable(a){a=mergeWithDefault(a,{left:0,top:0,visible:true,theta:0});this.left=a.left;this.top=a.top;this.visible=a.visible;this.theta=a.theta}Drawable.prototype.draw=function(){console.log("ERROR: Calling unimplemented draw method on drawable object.")};
function Primitive(a){a=mergeWithDefault(a,{lineWidth:1,color:"black"});Drawable.call(this,a);this.lineWidth=a.lineWidth;this.color=a.color}Primitive.inheritsFrom(Drawable);function Text(a){a=mergeWithDefault(a,{content:"",fill:"black",font:"12pt Helvetica",height:12});Drawable.call(this,a);this.content=a.content;this.fill=a.fill;this.font=a.font;this.height=a.height}Text.inheritsFrom(Drawable);
Text.prototype.draw=function(a){a.fillStyle=this.fill;a.font=this.font;a.fillText(this.content,this.left,this.height)};function DoodleImage(a){a=mergeWithDefault(a,{width:-1,height:-1,src:""});Drawable.call(this,a);this.width=a.width;this.height=a.height;this.src=a.src}DoodleImage.inheritsFrom(Drawable);DoodleImage.prototype.draw=function(a){var b=new Image,c=this.left,d=this.top,e=this.width,f=this.height;b.src=this.src;e!=-1&&f!=-1?a.drawImage(b,c,d,e,f):a.drawImage(b,c,d)};
function Line(a){a=mergeWithDefault(a,{startX:0,startY:0,endX:0,endY:0,lineWidth:1});Primitive.call(this,a);this.startX=a.startX;this.startY=a.startY;this.endX=a.endX;this.endY=a.endY;this.lineWidth=a.lineWidth}Line.inheritsFrom(Primitive);Line.prototype.draw=function(a){a.beginPath();if(typeof this.lineWidth!="undefined")a.lineWidth=this.lineWidth;if(typeof this.color!="undefined")a.strokeStyle=this.color;a.moveTo(this.startX,this.startY);a.lineTo(this.endX,this.endY);a.closePath();a.stroke()};
function Path(a){a=mergeWithDefault(a,{type:"straight",points:[],fill:""});Primitive.call(this,a);this.type=a.type;this.points=a.points;this.fill=a.fill}Path.inheritsFrom(Primitive);
Path.prototype.draw=function(a){if(this.points.length>0){a.beginPath();a.moveTo(this.points[0].x,this.points[0].y);if(typeof this.lineWidth!="undefined")a.lineWidth=this.lineWidth;if(typeof this.color!="undefined")a.strokeStyle=this.color;if(this.fill!="")a.fillStyle=this.fill;switch(this.type){case "straight":for(var b=1;b<this.points.length;b++){var c=this.points[b];a.lineTo(c.x,c.y)}break;case "quadratic":for(b=1;b<this.points.length;b++)c=this.points[b],a.quadraticCurveTo(c.cp1x,c.cp1y,c.x,c.y);
break;case "bezier":for(b=1;b<this.points.length;b++)c=this.points[b],a.bezierCurveTo(c.cp1x,c.cp1y,c.cp2x,c.cp2y,c.x,c.y)}this.fill!=""?a.fill():a.stroke()}};
function Arc(a){a=mergeWithDefault(a,{centerX:0,centerY:0,radius:0,startingTheta:0,endingTheta:0,counterclockwise:false,fill:""});Primitive.call(this,a);this.centerX=a.centerX;this.centerY=a.centerY;this.radius=a.radius;this.startingTheta=a.startingTheta;this.endingTheta=a.endingTheta;this.counterclockwise=a.counterclockwise;this.left=a.centerX-a.radius;this.top=a.centerY-a.radius;this.fill=a.fill}Arc.inheritsFrom(Primitive);
Arc.prototype.draw=function(a){a.beginPath();if(typeof this.lineWidth!="undefined")a.lineWidth=this.lineWidth;if(typeof this.color!="undefined")a.strokeStyle=this.color;a.arc(this.centerX,this.centerY,this.radius,this.startingTheta,this.endingTheta,this.counterclockwise);if(this.fill!="")a.fillStyle=this.fill,a.fill();a.stroke()};
function Container(a){a=mergeWithDefault(a,{width:100,height:100,fill:"",borderColor:"black",borderWidth:0,gradient:"",xVelocity:0,yVelocity:0});Drawable.call(this,a);this.children=[];this.width=a.width;this.height=a.height;this.fill=a.fill;this.borderColor=a.borderColor;this.borderWidth=a.borderWidth;this.gradient=a.gradient;this.xVelocity=a.xVelocity;this.yVelocity=a.yVelocity}Container.inheritsFrom(Drawable);
Container.prototype.draw=function(a){a.save();if(this.borderWidth!=0)a.lineWidth=this.borderWidth;a.translate(this.left,this.top);a.rotate(this.theta);a.beginPath();a.moveTo(0,0);a.lineTo(this.width,0);a.lineTo(this.width,this.height);a.lineTo(0,this.height);a.lineTo(0,0);a.closePath();if(this.fill!="")a.fillStyle=this.fill,a.fill();if(this.gradient!=""){for(var b=a.createLinearGradient(0,0,this.width,this.height),c=0;c<this.gradient.length;c++){var d=this.gradient[c];b.addColorStop(d.position,d.color)}a.fillStyle=
b;a.fill()}this.borderWidth!=0&&a.stroke();a.clip();for(c=0;c<this.children.length;c++)b=this.children[c],a.save(),b.draw(a),a.restore();a.restore()};function PolygonContainer(a){a=mergeWithDefault(a,{radius:100,sides:3,centerX:100,centerY:100,polygonTheta:0});Container.call(this,a);this.radius=a.radius;this.sides=a.sides;this.centerX=a.centerX;this.centerY=a.centerY;this.polygonTheta=a.polygonTheta;this.left=a.centerX-a.radius;this.top=a.centerY-a.radius}PolygonContainer.inheritsFrom(Container);
PolygonContainer.prototype.draw=function(a){a.save();if(this.borderWidth!=0)a.lineWidth=this.borderWidth;if(typeof this.borderColor!="undefined")a.strokeStyle=this.borderColor;if(typeof this.fill!="undefined")a.fillStyle=this.fill;a.save();a.translate(this.centerX,this.centerY);a.rotate(-this.polygonTheta);var b=360/this.sides*(Math.PI/180);a.beginPath();a.moveTo(this.radius,0);for(var c=1;c<=this.sides;c++){var d=b*c,e=this.radius*Math.cos(d),d=this.radius*Math.sin(d);a.lineTo(e,d)}a.closePath();
a.fill();a.stroke();a.clip();a.restore();a.save();a.translate(this.left,this.top);for(c=0;c<this.children.length;c++)b=this.children[c],a.save(),b.draw(a),a.restore();a.restore();a.restore()};
var _canvas_width=800,_canvas_height=500,_doodle=void 0,_ground=void 0,_truck_container=void 0,_arrows=[],_balloons=[],_time_step=10,_time_s_to_ms=_time_step/1E3,_gravity=5,_gravity_increment=_gravity*_time_s_to_ms,_power=8,_kill_radius=12,_fire=false,_score=void 0,_balloon_min_x=1,_balloon_max_x=3,_arrow_degree_vary=0.1;
window.onload=function(){var a=document.getElementById("canvas"),b=a.getContext("2d");a.style.width=_canvas_width+"px";a.style.height=_canvas_height+"px";a.width=_canvas_width;a.height=_canvas_height;_doodle=new Doodle(b);_ground=new Container({width:_canvas_width,height:50,left:0,fill:"brown",top:_canvas_height-50,borderWidth:2});_truck_container=new Container({width:80,height:80,left:10,top:_canvas_height-_ground.height-80,borderWidth:0});_launcher=new Container({top:55,left:10,width:40,height:10,
theta:-Math.PI/3,fill:"#156100",borderWidth:1});var a=new Arc({centerX:11,centerY:72,lineWidth:1,radius:7,fill:"#333",startingTheta:0,endingTheta:Math.PI*2}),b=new Arc({centerX:28,centerY:72,lineWidth:1,radius:7,fill:"#333",startingTheta:0,endingTheta:Math.PI*2}),c=new Arc({centerX:68,centerY:72,lineWidth:1,fill:"#333",radius:7,startingTheta:0,endingTheta:Math.PI*2}),d=new Container({top:60,left:0,height:8,width:80,fill:"#156100",borderWidth:1});_truck_container.children=[a,b,c,d,_launcher];a=new Text({left:20,
height:40,content:"Score: "});_score=new Text({left:80,height:40,content:"0"});_doodle.children=[a,_score,_ground,_truck_container];_doodle.draw();window.addEventListener("keydown",doKeyDown,true);setInterval(createBalloons,2E3);setInterval(updateAndDraw,_time_step)};
function createBalloons(){var a=new Container({top:Math.random()*(_canvas_height-70),left:_canvas_width+10,height:16,width:16,borderWidth:0,xVelocity:_balloon_min_x+Math.random()*(_balloon_max_x-_balloon_min_x)}),b=new Arc({centerX:8,centerY:8,lineWidth:1,fill:"red",radius:6,startingTheta:0,endingTheta:Math.PI*2});a.children=[b];_doodle.children.push(a);_balloons.push(a)}
function moveBalloons(){for(var a=0;a<_balloons.length;a++){var b=_balloons[a];b.left-=b.xVelocity;if(b.left+15<0){_balloons.splice(a,1);for(var c=0;c<_doodle.children.length;c++)_doodle.children[c]==b&&_doodle.children.splice(c,1)}}}
function killBalloons(){for(var a=0;a<_balloons.length;a++)for(var b=_balloons[a],c=0;c<_arrows.length;c++){var d=_arrows[c];if(Math.abs(b.left-d.left)<=_kill_radius&&Math.abs(b.top-d.top)<=_kill_radius){_balloons.splice(a,1);for(d=0;d<_doodle.children.length;d++)if(_doodle.children[d]==b)_doodle.children.splice(d,1),_score.content=parseInt(_score.content,10)+1}}}
function updateAndDraw(){_doodle.context.clearRect(0,0,_canvas_width,_canvas_height-50);killBalloons();moveBalloons();moveArrows();_doodle.draw()}
function moveArrows(){for(var a=0;a<_arrows.length;a++){var b=_arrows[a];if(b.top<_canvas_height&&b.left<_canvas_width){b.yVelocity+=_gravity_increment;var c=b.left,d=b.top,c=Math.atan((d+b.yVelocity-d)/(c+b.xVelocity-c));b.left+=b.xVelocity;b.top+=b.yVelocity;b.theta=c}else{_arrows.splice(a,1);for(c=0;c<_doodle.children.length;c++)_doodle.children[c]==b&&_doodle.children.splice(c,1)}}}
function doKeyDown(a){switch(a.keyCode){case 38:if(_launcher.theta+Math.PI/2>0.2&&(_dirty=true,_launcher.theta-=0.05,!_fire))_arrow_container.theta=_launcher.theta,_arrow_container.xVelocity=_power*Math.cos(-1*_arrow_container.theta),_arrow_container.yVelocity=-1*_power*Math.sin(-1*_arrow_container.theta);break;case 40:if(_launcher.theta<-0.05&&(_launcher.theta+=0.05,!_fire))_arrow_container.theta=_launcher.theta,_arrow_container.xVelocity=_power*Math.cos(-1*_arrow_container.theta),_arrow_container.yVelocity=
-1*_power*Math.sin(-1*_arrow_container.theta);break;case 37:if(_truck_container.left>5&&(_truck_container.left-=3,!_fire))_arrow_container.left=_truck_container.left+_launcher.left;break;case 39:if(_canvas_width-_truck_container.left+_truck_container.width>5&&(_truck_container.left+=3,!_fire))_arrow_container.left=_truck_container.left+_launcher.left;break;case 32:createArrow()}}
function createArrow(){var a=new Container({width:18,height:6,left:_truck_container.left+_launcher.left,top:_truck_container.top+_launcher.top,theta:_launcher.theta+Math.random()*_arrow_degree_vary,borderWidth:0,xVelocity:_power*Math.cos(-1*(_launcher.theta+Math.random()*_arrow_degree_vary)),yVelocity:-1*_power*Math.sin(-1*(_launcher.theta+Math.random()*_arrow_degree_vary))}),b=new Line({startX:2,startY:3,endX:16,endY:3,lineWidth:1}),c=new Path({color:"black",fill:"black",lineWidth:1,type:"straight",
points:[{x:18,y:3},{x:15,y:0},{x:15,y:6}]}),d=new Path({color:"black",lineWidth:1,type:"straight",points:[{x:0,y:1},{x:4,y:3},{x:0,y:5}]});a.children=[d,b,c];_arrows.push(a);_doodle.children.push(a)};